// src/lib/components/features/Footer.svelte
<script lang="ts">
    import ComLinkedin from "../icons/ComLinkedin.svelte";
    import ComGithub from "../icons/ComGithub.svelte";
    import Mail from "../icons/Mail.svelte";
    import RSS from "../icons/RSS.svelte";
    import A from "../typography/A.svelte";
</script>

<style>
    footer {
        background-color: #ebebeb;
        width: 100%;
    }

    :global(.dark) {
        footer {
            background-color: #1c1c1c;
        }
    }

    nav {
        display: flex;
        justify-content: center;
        column-gap: 25px;
        padding: 12px;
    }

    div {
        color: black;
    }

    :global(.dark) {
        div {
            color: white;
        }
    }
</style>

<footer>
    <nav>
        <A href="http://github.com/joao-arthur" target="_blank">
            <div>
                <ComGithub size={50}></ComGithub>
            </div>
        </A>
        <A href="https://www.linkedin.com/in/joao-lothamer" target="_blank">
            <div>
                <ComLinkedin size={50}></ComLinkedin>
            </div>
        </A>
        <A href="mailto://joao.lothamer@gmail.com" target="_blank">
            <div>
                <Mail size={50}></Mail>
            </div>
        </A>
        <A href="https://joao-arthur.dev/api/rss.xml" target="_blank">
            <div>
                <RSS size={50}></RSS>
            </div>
        </A>
    </nav>
</footer>

// src/components/Footer.tsx
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai';

export function Footer() {
    return (
        <footer className='flex justify-center pb-2 items-center'>
            <a className='mx-3'
                href="http://github.com/joao-arthur"
                target="_blank"
                rel="noopener noreferrer">
                <AiFillGithub size={30} />
            </a>
            <a
                className='mx-3'
                href="https://www.linkedin.com/in/joao-lothamer"
                target="_blank"
                rel="noopener noreferrer">
                <AiFillLinkedin size={30} />
            </a>
            <span className='mx-3 select-none'>João Arthur</span>
        </footer>
    );
}
