// src/components/Card.tsx
import type { JSX } from "react";
import { cl } from "../lib/cl";

type Props = {
    readonly children: JSX.Element | readonly JSX.Element[];
};

export function Card({ children }: Props): JSX.Element {
    const dark = "#0369a1";
    const light = "#0ea5e9";

    return (
        <div
            className={cl(
                "overflow-hidden",
                "p-6",
                "rounded-3xl",
                "border-sky-600 active:border-sky-700",
                "bg-sky-100 active:bg-sky-200",
            )}
            style={{
                background: `linear-gradient(135deg, ${light}, ${dark})`,
            }}
        >
            {children}
        </div>
    );
}

// src/lib/components/design/Card.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    type Props = {
        readonly children: Snippet;
        readonly title?: string;
    };

    const { children, title }: Props = $props();
</script>

<style>
    li {
        max-width: 800px;
        min-width: 0px;
        border-radius: 20px;
        overflow: hidden;
        list-style: none;
        background-color: var(--surface-light);
    }

    :global(.dark) {
        li {
            background-color: var(--surface-dark);
        }
    }
</style>

<li {title}>
    {@render children?.()}
</li>
