// src/features/Footer.tsx
import type { JSX } from "react";
import { FaGithubAlt, FaLinkedinIn } from "react-icons/fa6";
import { MdEmail } from "react-icons/md";
import { Layout } from "../components/Layout";
import { cl } from "../lib/cl";

export function Footer(): JSX.Element {
    return (
        <div className="w-full flex flex-col">
            <div
                className={cl(
                    "w-full h-20",
                    "flex justify-center items-center gap-x-5",
                    "bg-prm-40 dark:bg-prm-15",
                )}
            >
                <Layout.Button>
                    <a
                        href="http://github.com/joao-arthur"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <FaGithubAlt size={30} className="w-16 h-16 p-4" color="white" />
                    </a>
                </Layout.Button>
                <Layout.Button>
                    <a
                        href="https://www.linkedin.com/in/joao-lothamer"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <FaLinkedinIn size={30} className="w-16 h-16 p-4" color="white" />
                    </a>
                </Layout.Button>
                <Layout.Button>
                    <a
                        href="mailto://joao.lothamer@gmail.com"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <MdEmail size={30} className="w-16 h-16 p-4" color="white" />
                    </a>
                </Layout.Button>
            </div>
        </div>
    );
}

// src/lib/components/features/Footer.svelte
<script lang="ts">
    import ComLinkedin from "../icons/ComLinkedin.svelte";
    import ComGithub from "../icons/ComGithub.svelte";
    import Mail from "../icons/Mail.svelte";
    import RSS from "../icons/RSS.svelte";
    import A from "../typography/A.svelte";
</script>

<style>
    footer {
        background-color: #ebebeb;
        width: 100%;
    }

    :global(.dark) {
        footer {
            background-color: #1c1c1c;
        }
    }

    nav {
        display: flex;
        justify-content: center;
        column-gap: 25px;
        padding: 12px;
    }

    div {
        color: black;
    }

    :global(.dark) {
        div {
            color: white;
        }
    }
</style>

<footer>
    <nav>
        <A href="http://github.com/joao-arthur" target="_blank">
            <div>
                <ComGithub size={50}></ComGithub>
            </div>
        </A>
        <A href="https://www.linkedin.com/in/joao-lothamer" target="_blank">
            <div>
                <ComLinkedin size={50}></ComLinkedin>
            </div>
        </A>
        <A href="mailto://joao.lothamer@gmail.com" target="_blank">
            <div>
                <Mail size={50}></Mail>
            </div>
        </A>
        <A href="https://joao-arthur.dev/api/rss.xml" target="_blank">
            <div>
                <RSS size={50}></RSS>
            </div>
        </A>
    </nav>
</footer>
