// src/lib/components/features/blog.svelte
<script lang="ts">
    import type { BlogPost, Language } from "$lib/src/types";
    import Card from "$lib/components/design/Card.svelte";
    import Content from "$lib/components/layout/Content.svelte";
    import H1 from "$lib/components/design/typography/H1.svelte";
    import P from "$lib/components/design/typography/P.svelte";
    import Badge from "$lib/components/design/Badge.svelte";
    import CardContent from "$lib/components/design/CardContent.svelte";
    import BadgeContainer from "$lib/components/design/BadgeContainer.svelte";
    import A from "$lib/components/design/typography/A.svelte";

    type Props = {
        readonly language: Language;
        readonly posts: readonly BlogPost[];
    }

    let { posts, language }: Props = $props();
</script>

<Content>
    {#each posts as post}
        <Card>
            <CardContent>
                <A href="/{language}/blog/{post.slug}">
                    <H1>{post.title}</H1>
                    <P>{post.description}</P>
                    <P>{new Date(post.created_at).toLocaleDateString()}</P>
                </A>
                <BadgeContainer>
                    {#each post.technologies as technology}
                        <Badge color="blue">{technology}</Badge>
                    {/each}
                </BadgeContainer>
            </CardContent>
        </Card>
    {/each}
</Content>

// src/app/blog/page.tsx
import type { JSX } from "react";
import type { BlogPost } from "../../lib/types";
import { Metadata } from "next";
import Link from "next/link";
import { Card, CardContent, Typography } from "@mui/material";
import { Layout } from "../../components/Layout";

export const metadata: Metadata = {
    title: "Blog | João Arthur",
};

export default async function BlogPage(): Promise<JSX.Element> {
    const posts: readonly BlogPost[] = await fetch(
        "https://raw.githubusercontent.com/joao-arthur/assets/main/blog.json",
        { cache: "force-cache" },
    ).then((res) => res.json());

    return (
        <Layout.Content>
            {posts.map((post) => (
                <Link key={post.id} href={`/blog/post/${post.id}`}>
                    <Card variant="elevation">
                        <CardContent>
                            <div className="h-40 w-full">
                                <Typography variant="h4">{post.name.en}</Typography>
                                <Typography variant="h6">{post.date}</Typography>
                            </div>
                        </CardContent>
                    </Card>
                </Link>
            ))}
        </Layout.Content>
    );
}
