// src/features/Footer.tsx
import type { JSX } from "react";
import { FaGithubAlt, FaLinkedinIn } from "react-icons/fa6";
import { MdEmail } from "react-icons/md";
import { Layout } from "../components/Layout";
import { cl } from "../lib/cl";

export function Footer(): JSX.Element {
    return (
        <div className="w-full flex flex-col">
            <div className="w-full h-3 bg-prm-40 dark:bg-prm-15" />
            <div className={cl(
                "w-full h-24",
                "flex justify-center items-center gap-x-5",
                "bg-prm-50 dark:bg-prm-20"
                )}>
                <Layout.Button>
                    <a
                        href="http://github.com/joao-arthur"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <FaGithubAlt size={30} className="w-16 h-16 p-4" color="#fecdd3" />
                    </a>
                </Layout.Button>
                <Layout.Button>
                    <a
                        href="https://www.linkedin.com/in/joao-lothamer"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <FaLinkedinIn size={30} className="w-16 h-16 p-4" color="#fecdd3" />
                    </a>
                </Layout.Button>
                <Layout.Button>
                    <a
                        href="mailto://joao.lothamer@gmail.com"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <MdEmail size={30} className="w-16 h-16 p-4" color="#fecdd3" />
                    </a>
                </Layout.Button>
            </div>
        </div>
    );
}

// src/lib/components/layout/Footer.svelte
<script lang="ts">
    import ComLinkedin from "../design/icons/ComLinkedin.svelte";
    import ComGithub from "../design/icons/ComGithub.svelte";
    import Mail from "../design/icons/Mail.svelte";
    import RSS from "../design/icons/RSS.svelte";
    import A from "../design/typography/A.svelte";
</script>

<style>
    footer {
        width: 100%;
        padding-bottom: 2rem;
        background-color: var(--color-prm-72);
    }

    :global(.dark) {
        footer {
            background-color: var(--color-prm-8);
        }
    }

    nav {
        display: flex;
        justify-content: center;
        column-gap: 25px;
        padding: 12px;
    }

    div {
        color: var(--color-prm-20);
    }

    div:hover {
        color: var(--color-prm-28);
    }

    div:active {
        color: var(--color-prm-36);
    }

    :global(.dark) {
        div {
            color: var(--color-prm-72);
        }

        div:hover {
            color: var(--color-prm-60);
        }

        div:active {
            color: var(--color-prm-52);
        }
    }
</style>

<footer>
    <nav>
        <A href="http://github.com/joao-arthur" target="_blank">
            <div>
                <ComGithub size={50}></ComGithub>
            </div>
        </A>
        <A href="https://www.linkedin.com/in/joao-lothamer" target="_blank">
            <div>
                <ComLinkedin size={50}></ComLinkedin>
            </div>
        </A>
        <A href="mailto://joao.lothamer@gmail.com" target="_blank">
            <div>
                <Mail size={50}></Mail>
            </div>
        </A>
        <A href="https://joao-arthur.dev/api/rss.xml" target="_blank">
            <div>
                <RSS size={50}></RSS>
            </div>
        </A>
    </nav>
</footer>
